### ISSUE TITLE
Percentage of loss as part of result

### ISSUE THREAD

**Issue by KyleMaas** [piderman314/bardecoder#26]
It would be really handy if, when a barcode is returned, the percentage of bits which had to be corrected could be returned as well.  At least for my current application, this information would be really useful to have.

**Comment by piderman314** [comment]
Hey, I have implemented a new version of the decoder that also returns some info about the qr. You can replace `default_decoder()` with `default_decoder_with_info()` and instead of a `String` result you get a tuple `(String, QRInfo)`. Said info contains the version, ec_level, total number of bits in the QR Code and number of bits of error corrected.

The data/error counts include both the actual data and error correction data. The error correction algorithm doesn't make a distinction, and usually the actual data doesn't contain nearly the entire capacity anyway.

**Comment by KyleMaas** [comment]
Excellent.  I look forward to trying it.  Thank you!
