### ISSUE TITLE
Can't detect this qr code even with manually drawn features

### ISSUE THREAD

**Issue by jounathaen** [piderman314/bardecoder#32]
I have this QR code which can't be detected:

![82](https://user-images.githubusercontent.com/16337548/106462221-14b1ca00-6496-11eb-9d8b-05c59ac90ece.png)

The candidates debug Image looks as follows:

![candidates](https://user-images.githubusercontent.com/16337548/106462279-26936d00-6496-11eb-8c3b-38ca57f3e752.png)

Ok, then let's repaint the "corner boxes" with pixel-perfect ones in a paint programm:

![test](https://user-images.githubusercontent.com/16337548/106462442-60647380-6496-11eb-8a48-70facc752e85.png)

But still no success... :disappointed: 

![candidates](https://user-images.githubusercontent.com/16337548/106462495-783bf780-6496-11eb-98ce-325218488020.png)

The code is 1:1 the example from the README.md

BTW: zxing and zbar fail for the unedited code but succeed with the hand drawn corner features

**Comment by piderman314** [comment]
I think the problem with this image is that the black parts are too wide. In almost all instances, including the locator patterns, the black squares are about 7-8 pixels wide, while the white squares are 5-6 pixels wide. This throws off the algorithm because it expects the white and black parts to be the same size. The algorithm has some tolerances built-in, but we're looking at over 25% bigger black squares, which is too much.

**Comment by jounathaen** [comment]
Hmmm, that might be the reason. A bit dissatisfying because I can't really change the input but then I'll have to find some other way... Feel free to close this if you think this case is out of scope :slightly_smiling_face:

**Comment by piderman314** [comment]
I'm sorry I can't help you with this. Unfortunately sometimes QR Codes are created that do not adhere to the specs, which makes it difficult or impossible to read them properly.
